### PR TITLE
Eval splits

### PR DESCRIPTION
**Pull request by JLrumberger**
**What is the purpose of this PR?**

Added eval split jsons for hickey and msk_pancreas

**Remaining issues**

None

### CODE REVIEW

**Comment by JLrumberger** [comment]
Hi @srivarra,
the build fails on travis but not locally. I reran Travis CI - Branch on main and it also fails now, even though it passed just a couple of days ago. The error message is `ImportError: cannot import name 'Config' from 'pytest' (/home/travis/virtualenv/python3.9.12/lib/python3.9/site-packages/pytest/__init__.py)`. I googled it and found [this messy stackoverflow thread](https://stackoverflow.com/questions/41748464/pytest-cannot-import-module-while-python-can), but both of their proposed solutions (getting rid of __init__.py at the top level or adding conftest.py) are already in place. Do you have an idea on how to fix it or already experienced this error?

**Comment by srivarra** [comment]
@JLrumberger We removed Travis from all the other repos, and I'm working on getting GitHub actions on this repo!

**Comment by JLrumberger** [comment]
Oh! Thanks for letting me know.

**Comment by ngreenwald** [comment]
As long as everything is passing locally we can merge it in once you're ready

**Comment by JLrumberger** [comment]
Branch had conflicts with main. I made a new branch and added the changes, so this PR can be closed.

**Pull request closed without merging**
